# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/vertex_simulation/',
                'doc_host': 'https://mshagirov.github.io',
                'git_url': 'https://github.com/mshagirov/vertex_simulation/tree/master/',
                'lib_path': 'vertex_simulation'},
  'syms': {'vertex_simulation.primitives': {}, 'vertex_simulation.simulation': {}, 'vertex_simulation.vertex_dynamics_models': {}}}
