# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_graph": "00_primitives.ipynb",
         "VoronoiRegions2Edges": "00_primitives.ipynb",
         "Vertex": "00_primitives.ipynb",
         "Graph": "00_primitives.ipynb",
         "Monolayer": "00_primitives.ipynb",
         "unit_hexagons": "01_simulation.ipynb"}

modules = ["primitives.py",
           "simulation.py"]

doc_url = "https://mshagirov.github.io/vertex_simulation/"

git_url = "https://github.com/mshagirov/vertex_simulation/tree/master/"

def custom_doc_links(name): return None