#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Vertex": "00_primitives.ipynb",
         "Graph": "00_primitives.ipynb",
         "plot_graph": "00_primitives.ipynb",
         "Monolayer": "00_primitives.ipynb",
         "VoronoiRegions2Edges": "00_primitives.ipynb"}

modules = ["primitives.py"]

git_url = "https://github.com/mshagirov/vertex_simulation/tree/master/"

def custom_doc_links(name): return None