# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_simulation.ipynb (unless otherwise specified).

__all__ = ['unit_hexagons']

# Cell
import torch, numpy as np, matplotlib.pylab as plt
from scipy.spatial import Voronoi,voronoi_plot_2d

# Cell
def unit_hexagons(Nx,Ny):
    '''Produces hexagons with unit length edges, arranged in a hexagonal lattice.'''
    # for regular hexagons with unit length edges
    dXY = [np.sqrt(3), 1.5] # original grid spacing
    x_offset = np.sqrt(3)/2 # moves alter-g rows to the right (+ x-axis)
    X,Y = np.meshgrid(np.linspace(0,(Nx-1)*dXY[0],Nx),np.linspace(0,(Ny-1)*dXY[1],Ny))
    X[1::2,:]+=x_offset
    Xlpad =  0
    # Seeds for Voronoi
    Xseed = np.concatenate((X.ravel()[:,np.newaxis],Y.ravel()[:,np.newaxis]),axis=1)
    vrn = Voronoi(Xseed)

    return vrn

